<?php
/**
 * @package slt
 */
?>

<div class="secondline-themes-social-icons">
	
	<?php if (get_theme_mod( 'secondline_themes_header_facebook')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_facebook')); ?>" target="_blank" class="secondline-themes-facebook" title="<?php echo esc_attr__( 'Facebook', 'tusant-secondline' ); ?>"><i class="fab fa-facebook-f"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_twitter')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_twitter')); ?>" target="_blank" class="secondline-themes-twitter" title="<?php echo esc_attr__( 'Twitter', 'tusant-secondline' ); ?>"><i class="fab fa-twitter"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_instagram')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_instagram')); ?>" target="_blank" class="secondline-themes-instagram" title="<?php echo esc_attr__( 'Instagram', 'tusant-secondline' ); ?>"><i class="fab fa-instagram"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_spotify')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_spotify')); ?>" target="_blank" class="secondline-themes-spotify" title="<?php echo esc_attr__( 'Spotify', 'tusant-secondline' ); ?>"><i class="fab fa-spotify"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_youtube' )) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_youtube')); ?>" target="_blank" class="secondline-themes-youtube" title="<?php echo esc_attr__( 'Youtube', 'tusant-secondline' ); ?>"><i class="fab fa-youtube"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_vimeo')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_vimeo')); ?>" target="_blank" class="secondline-themes-vimeo" title="<?php echo esc_attr__( 'Vimeo', 'tusant-secondline' ); ?>"><i class="fab fa-vimeo"></i></a><?php endif; ?>	
	<?php if (get_theme_mod( 'secondline_themes_header_rss')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_rss')); ?>" target="_blank" class="secondline-themes-rss" title="<?php echo esc_attr__( 'RSS', 'tusant-secondline' ); ?>"><i class="fa fa-rss"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_itunes')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_itunes')); ?>" target="_blank" class="secondline-themes-itunes" title="<?php echo esc_attr__( 'Podcast', 'tusant-secondline' ); ?>"><i class="fa fa-podcast"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_android')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_android')); ?>" target="_blank" class="secondline-themes-android" title="<?php echo esc_attr__( 'Android', 'tusant-secondline' ); ?>"><i class="fab fa-android"></i></a><?php endif; ?>
    <?php if (get_theme_mod( 'secondline_themes_header_patreon')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_patreon')); ?>" target="_blank" class="secondline-themes-patreon" title="<?php echo esc_attr__( 'Patreon', 'tusant-secondline' ); ?>"><i class="fab fa-patreon"></i></a><?php endif; ?>	
	<?php if (get_theme_mod( 'secondline_themes_header_pinterest')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_pinterest')); ?>" target="_blank" class="secondline-themes-pinterest" title="<?php echo esc_attr__( 'Pinterest', 'tusant-secondline' ); ?>"><i class="fab fa-pinterest"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_soundcloud')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_soundcloud')); ?>" target="_blank" class="secondline-themes-soundcloud" title="<?php echo esc_attr__( 'Soundcloud', 'tusant-secondline' ); ?>"><i class="fab fa-soundcloud"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_linkedin')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_linkedin')); ?>" target="_blank" class="secondline-themes-linkedin" title="<?php echo esc_attr__( 'LinkedIn', 'tusant-secondline' ); ?>"><i class="fab fa-linkedin"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_snapchat')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_snapchat')); ?>" target="_blank" class="secondline-themes-snapchat" title="<?php echo esc_attr__( 'Snapchat', 'tusant-secondline' ); ?>"><i class="fab fa-snapchat-ghost"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_tumblr')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_tumblr')); ?>" target="_blank" class="secondline-themes-tumblr" title="<?php echo esc_attr__( 'Tumblr', 'tusant-secondline' ); ?>"><i class="fab fa-tumblr"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_flickr')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_flickr')); ?>" target="_blank" class="secondline-themes-flickr" title="<?php echo esc_attr__( 'Flickr', 'tusant-secondline' ); ?>"><i class="fab fa-flickr"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_dribbble')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_dribbble')); ?>" target="_blank" class="secondline-themes-dribbble" title="<?php echo esc_attr__( 'Dribbble', 'tusant-secondline' ); ?>"><i class="fab fa-dribbble"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_vk')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_vk')); ?>" target="_blank" class="secondline-themes-vk" title="<?php echo esc_attr__( 'VK', 'tusant-secondline' ); ?>"><i class="fab fa-vk"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_wordpress')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_wordpress')); ?>" target="_blank" class="secondline-themes-wordpress" title="<?php echo esc_attr__( 'WordPress', 'tusant-secondline' ); ?>"><i class="fab fa-wordpress"></i></a><?php endif; ?>
	
	<?php if (get_theme_mod( 'secondline_themes_header_mixcloud')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_mixcloud')); ?>" target="_blank" class="secondline-themes-mixcloud" title="<?php echo esc_attr__( 'MixCloud', 'tusant-secondline' ); ?>"><i class="fab fa-mixcloud"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_behance')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_behance')); ?>" target="_blank" class="secondline-themes-behance" title="<?php echo esc_attr__( 'Behance', 'tusant-secondline' ); ?>"><i class="fab fa-behance"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_github')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_github')); ?>" target="_blank" class="secondline-themes-github" title="<?php echo esc_attr__( 'Github', 'tusant-secondline' ); ?>"><i class="fab fa-github"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_lastfm')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_lastfm')); ?>" target="_blank" class="secondline-themes-lastfm" title="<?php echo esc_attr__( 'LastFM', 'tusant-secondline' ); ?>"><i class="fab fa-lastfm"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_medium')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_medium')); ?>" target="_blank" class="secondline-themes-medium" title="<?php echo esc_attr__( 'Medium', 'tusant-secondline' ); ?>"><i class="fab fa-medium"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_reddit')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_reddit')); ?>" target="_blank" class="secondline-themes-reddit" title="<?php echo esc_attr__( 'Reddit', 'tusant-secondline' ); ?>"><i class="fab fa-reddit"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_tripadvisor')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_tripadvisor')); ?>" target="_blank" class="secondline-themes-tripadvisor" title="<?php echo esc_attr__( 'Trip Advisor', 'tusant-secondline' ); ?>"><i class="fab fa-tripadvisor"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_twitch')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_twitch')); ?>" target="_blank" class="secondline-themes-twitch" title="<?php echo esc_attr__( 'Twitch', 'tusant-secondline' ); ?>"><i class="fab fa-twitch"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_yelp')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_yelp')); ?>" target="_blank" class="secondline-themes-yelp" title="<?php echo esc_attr__( 'Yelp', 'tusant-secondline' ); ?>"><i class="fab fa-yelp"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'secondline_themes_header_discord')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_discord')); ?>" target="_blank" class="secondline-themes-discord" title="<?php echo esc_attr__( 'Discord', 'tusant-secondline' ); ?>"><i class="fab fa-discord"></i></a><?php endif; ?>	
	<?php if (get_theme_mod( 'secondline_themes_header_bandcamp')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_bandcamp')); ?>" target="_blank" class="secondline-themes-bandcamp" title="<?php echo esc_attr__( 'Bandcamp', 'tusant-secondline' ); ?>"><i class="fab fa-bandcamp"></i></a><?php endif; ?>		
	<?php if (get_theme_mod( 'secondline_themes_header_mail')) : ?><a href="mailto:<?php echo esc_attr(get_theme_mod('secondline_themes_header_mail')); ?>" class="secondline-themes-mail" title="<?php echo esc_attr__( 'Email', 'tusant-secondline' ); ?>"><i class="fa fa-envelope"></i></a><?php endif; ?>	
	<?php if (get_theme_mod( 'secondline_themes_header_wishlist')) : ?><a href="<?php echo esc_url(get_theme_mod('secondline_themes_header_wishlist')); ?>"  class="secondline-themes-wishlist" title="<?php echo esc_attr__( 'Wishlist', 'tusant-secondline' ); ?>"><i class="fa fa-heart" aria-hidden="true"></i></a><?php endif; ?>
	
	<div class="clearfix-slt"></div>
</div><!-- close .secondline-themes-social-icons -->